version: '3.8'

services:
  # 1. กล่องฐานข้อมูล PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: ku-wifi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ku_wifi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. กล่องเว็บ Super Admin (Node.js)
  superadmin-web:
    build: .
    container_name: ku-superadmin-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db # ชี้เป้าไปที่กล่อง Database ด้านบน

volumes:
  # พื้นที่เก็บข้อมูลไม่ให้หายเวลา Database ดับ
  pgdata: